version: "3.8"

services:
  backend:
    build:
      dockerfile: Dockerfile
    image: reflex-chat-rech-paper-backend:prod
    ports:
      - 8001:8000
    depends_on:
      - redis
    environment:
      - RAGFLOW_API_KEY=ragflow-IxZjFiZWZlYzEyMjExZWZhZjY2MDI0Mm
      - RAGFLOW_BASE_URL=http://192.168.1.39:9380
      - AGENT_NAME=ACRES Assistant
      - REDIS_URL=redis://redis:6379
      - API_URL=http://localhost:8001
    networks:
      - reflex_chat_network_rech

  frontend:
    image: reflex-chat-rech-paper-frontend:prod
    build:
      dockerfile: web.Dockerfile
    ports:
      - 3001:80
    depends_on:
      - backend
    networks:
      - reflex_chat_network_rech

  redis:
    image: redis
    networks:
        - reflex_chat_network_rech

networks:
  reflex_chat_network_rech:
    driver: bridge 
